export const socketString = {
  ADD_USER_TO_CHAT: "ADD_USER_TO_CHAT",
  REMOVE_USER_FROM_CHAT: "REMOVE_USER_FROM_CHAT",
  LEFT_ROOM: "LEFT_ROOM",
  NEW_MESSAGE: "new-message",

  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
};
